using System.Collections.Generic;

namespace Peasant.Core.Helpers;

public class Top100Ports
{
    public int Port { get; set; }
    public string Info { get; set; }

    public static List<Top100Ports> GetAllPorts()
    {
        return new List<Top100Ports>
        {
            new Top100Ports { Port = 20, Info = "FTP - Data" },
            new Top100Ports { Port = 21, Info = "FTP - Control" },
            new Top100Ports { Port = 22, Info = "SSH (Secure Shell)" },
            new Top100Ports { Port = 23, Info = "Telnet" },
            new Top100Ports { Port = 25, Info = "SMTP (Simple Mail Transfer Protocol)" },
            new Top100Ports { Port = 53, Info = "DNS (Domain Name System)" },
            new Top100Ports { Port = 67, Info = "DHCP (Dynamic Host Configuration Protocol) - Server" },
            new Top100Ports { Port = 68, Info = "DHCP (Dynamic Host Configuration Protocol) - Client" },
            new Top100Ports { Port = 69, Info = "TFTP (Trivial File Transfer Protocol)" },
            new Top100Ports { Port = 80, Info = "HTTP (Web)" },
            new Top100Ports { Port = 110, Info = "POP3 (Post Office Protocol)" },
            new Top100Ports { Port = 111, Info = "RPC (Remote Procedure Call)" },
            new Top100Ports { Port = 135, Info = "Microsoft RPC" },
            new Top100Ports { Port = 137, Info = "NetBIOS Name Service" },
            new Top100Ports { Port = 138, Info = "NetBIOS Datagram Service" },
            new Top100Ports { Port = 139, Info = "NetBIOS Session Service" },
            new Top100Ports { Port = 143, Info = "IMAP (Internet Message Access Protocol)" },
            new Top100Ports { Port = 161, Info = "SNMP (Simple Network Management Protocol)" },
            new Top100Ports { Port = 443, Info = "HTTPS (Secure Web)" },
            new Top100Ports { Port = 445, Info = "SMB (Server Message Block)" },
            new Top100Ports { Port = 514, Info = "Syslog" },
            new Top100Ports { Port = 587, Info = "SMTP (Secure/Authenticated)" },
            new Top100Ports { Port = 636, Info = "LDAP Secure (LDAPS)" },
            new Top100Ports { Port = 993, Info = "IMAPS (Secure IMAP)" },
            new Top100Ports { Port = 995, Info = "POP3S (Secure POP3)" },
            new Top100Ports { Port = 1433, Info = "Microsoft SQL Server" },
            new Top100Ports { Port = 1723, Info = "PPTP (VPN)" },
            new Top100Ports { Port = 3306, Info = "MySQL Database Server" },
            new Top100Ports { Port = 3389, Info = "RDP (Remote Desktop Protocol)" },
            new Top100Ports { Port = 4200, Info = "Angular Development Server" }, // Angular default port
            new Top100Ports { Port = 5900, Info = "VNC (Virtual Network Computing)" },
            new Top100Ports { Port = 8000, Info = "Django Development Server" }, // Django default port
            new Top100Ports { Port = 8080, Info = "HTTP Alternate (Web)" },
            new Top100Ports { Port = 8443, Info = "HTTPS Alternate (Secure Web)" },
            new Top100Ports { Port = 8888, Info = "HTTP Alternate (Web)" },
            new Top100Ports { Port = 9000, Info = "CSlistener (Backdoor)" },
            new Top100Ports { Port = 9090, Info = "WebSphere Application Server (Admin Console)" },
            new Top100Ports { Port = 9100, Info = "HP JetDirect" },
            new Top100Ports { Port = 9999, Info = "Bacula Director" },
            new Top100Ports { Port = 10000, Info = "Webmin" },
            new Top100Ports { Port = 49152, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49153, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49154, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49155, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49156, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49157, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49158, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49159, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49160, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49161, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49162, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49163, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49164, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49165, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49166, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49167, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49168, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49169, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49170, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49171, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49172, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49173, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49174, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49175, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49176, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49177, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49178, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49179, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49180, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49181, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49182, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49183, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49184, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49185, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49186, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49187, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49188, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49189, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49190, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49191, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49192, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49193, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49194, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49195, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49196, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49197, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49198, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49199, Info = "Windows RPC (Ephemeral)" },
            new Top100Ports { Port = 49200, Info = "Windows RPC (Ephemeral)" }
        };
    }
}